name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Style checks
        run: ./mill all __.checkFormat "__.fix --check" __.docJar

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Run tests
        run: ./mill __.test

  publish:
    needs: [checks, tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull all history with tags for correct versionning
        run: git fetch --prune --unshallow
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - uses: jodersky/setup-mill@master
        with:
          mill-version: 0.7.3
      - name: Publish
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') || github.event_name == 'release'
        env:
          SONATYPE_CREDENTIALS: ${{ secrets.SONATYPE_CREDENTIALS }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        run: |
          echo "${{ secrets.PGP_SECRET_KEY }}" | base64 --decode > private.key
          gpg --batch --yes --no-tty --import private.key
          rm private.key
          export GPG_TTY=$(tty)

          mill mill.scalalib.PublishModule/publishAll __.publishArtifacts novakov.alex:$SONATYPE_CREDENTIALS --gpgArgs --passphrase=$GPG_PASSWORD,--batch,--yes,-a,-b,--pinentry-mode,loopback