name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Style checks
        run: ./mill all __.checkFormat "__.fix --check" __.docJar

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Run tests
        run: ./mill __.test

  publish:
    needs: [checks, tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull all history with tags for correct versionning
        run: git fetch --prune --unshallow
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Publish
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') || github.event_name == 'release'
        run: |
          echo "${{ secrets.PGP_SECRET_KEY }}" > private.key
          gpg --batch --yes --import private.key
          rm private.key

          ./mill mill.scalalib.PublishModule/publishAll --sonatypeCreds ${{ secrets.SONATYPE_CREDENTIALS }} --publishArtifacts __.publishArtifacts --readTimeout 600000 --release true